apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kroger-mcp-infisical-secret
  namespace: kroger-mcp
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-bz-gt
        recursive: false
        secretsPath: /
  hostAPI: https://infisical.sirddail.net/api
  managedSecretReference:
    creationPolicy: Owner
    secretName: kroger-mcp-secrets
    secretNamespace: kroger-mcp
    secretType: Opaque
    template:
      data:
        KROGER_CLIENT_ID: '{{ .KROGER_CLIENT_ID.Value }}'
        KROGER_CLIENT_SECRET: '{{ .KROGER_CLIENT_SECRET.Value }}'
        KROGER_REDIRECT_URI: '{{ .KROGER_REDIRECT_URI.Value }}'
        KROGER_USER_ZIP_CODE: '{{ .KROGER_USER_ZIP_CODE.Value }}'
      includeAllSecrets: false
  resyncInterval: 60
